### ISSUE TITLE
error at launch

### ISSUE THREAD

**Issue by sype** [Wefactorit/docker-ci-img#7]
Maybe a i did something wrong but 
**i tried to launch the container :**
docker run -tdi wefactorit/ci-runner:0.0.1  bash

**i had this error :** 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.

It's a good start but i think like is missing a step we should be able to test the container is runnable before to push it to dockerhub

**Comment by shinsekai** [comment]
Indeed, I forgot to add bash to the image, my bad.

Yes it's a good idea, I'll create an ticket for this improvement.
